requirejs.config({
	paths: {
		main: 'main',
		OneWayModel: 'js/model/OneWayModel',
		OneWayNodeModel: 'js/model/OneWayNodeModel',
		OneWayController: 'js/controller/OneWayController',
		OneWay: 'js/view/OneWay',
		TwoWayModel: 'js/model/TwoWayModel',
		TwoWayNodeModel: 'js/model/TwoWayNodeModel',
		TwoWayController: 'js/controller/TwoWayController',
		TwoWay: 'js/view/TwoWay',
		QueueModel: 'js/model/QueueModel',
		QueueController: 'js/controller/QueueController',
		Queue: 'js/view/Queue',
		StackModel: 'js/model/StackModel',
		StackController: 'js/controller/StackController',
		Stack: 'js/view/Stack',
		TreeModel: 'js/model/TreeModel',
		TreeNodeModel: 'js/model/TreeNodeModel',
		Tree: 'js/view/Tree',
		BSTController: 'js/controller/BSTController',
		HeapModel: 'js/model/HeapModel',
		HeapController: 'js/controller/HeapController',
		PageController: 'js/controller/PageController',
		DataStructureFactory: 'js/designPatterns/factory/DataStructureFactory',
		Strategy: 'js/designPatterns/strategy/Strategy',
		State: 'js/designPatterns/state/State',
		Rotation: 'js/designPatterns/state/states/Rotation',
		FirstRotation: 'js/designPatterns/state/states/FirstRotation',
		SecondRotation: 'js/designPatterns/state/states/SecondRotation',
		ThirdRotation: 'js/designPatterns/state/states/ThirdRotation',
		FourthRotation: 'js/designPatterns/state/states/FourthRotation',
		LastRotation: 'js/designPatterns/state/states/LastRotation',
		TypesController: 'js/javaScript/TypesController',
		Types: 'js/view/Types',
		ClosuresController: 'js/javaScript/closures/ClosuresController',
		ClosureTest: 'js/javaScript/closures/ClosureTest',
		EventDispatcher: 'js/javaScript/events/EventDispatcher',
		Event: 'js/javaScript/events/Event',
		FunctionUtil: 'js/util/FunctionUtil',
		EventFlow: 'js/javaScript/events/EventFlow'
	}
});
require(['main']);